### ISSUE TITLE
Participation

### ISSUE THREAD

**Issue by GiperScriper** [borgbackup/borgweb#100]
Hello, i want offer help for refreshing (rewriting) borgweb (with react or angular) and add some features, this is actual?

**Comment by ThomasWaldmann** [comment]
Thanks for offering help. Why do you think it needs rewriting / refreshing? What features would need adding?

Maybe just file some more specific issues so we can discuss this better.

**Comment by GiperScriper** [comment]
Maybe you and your team have some ideas about improving ui, also it would be good to remove html rendering from flask, and make it like rest api

**Comment by ThomasWaldmann** [comment]
Why is it good to remove html rendering from flask? It works.

**Comment by ThomasWaldmann** [comment]
stale, closing.

we'ld like to get help with the UI, but it should be more specific about goals (not: "introduce technology X").
