### ISSUE TITLE
Question: can I change max_segments_size in the config file?

### ISSUE THREAD

**Issue by qlandman** [borgbackup/borgweb#101]
I have a question regarding the max_segments_size variable in the config file of a Borg repo. The default config size makes that created files in de data directory are approx. 5MB each. This is fine for backups stored on a local drive, but when I want to transfer the repo to a Webdav mount it is very slow due to the ramp up time for the file transfer.

Can I safely alter the max_segments_size variable without affecting the reliability of the Borg Backup process? What would be a sane size for each segment created. I was thinking of something between 20-50 MB for repos I want to store offsite.

**Comment by pguth** [comment]
Thanks! Please re-raise here: https://github.com/borgbackup/borg/issues
