### ISSUE TITLE
improve docs

### ISSUE THREAD

**Issue by dsjstc** [borgbackup/borgweb#102]
As a prospective user of Borg, my first question is "what's the search/retrieval system like?"  So I'd really love to be able to see what BorgWeb would look like, without having to install and configure Borg and BorgWeb.

**Comment by ThomasWaldmann** [comment]
https://borgweb.readthedocs.io/en/latest/ see screenshot there. that is pretty much all there is, see also project description.

**Comment by dsjstc** [comment]
Yup, the screenshot showing a bunch of errors is precisely what is insufficient for me to decide whether to do a test install!   The project description appears targeted to new co-developers, not a prospective user.

**Comment by ThomasWaldmann** [comment]
It only does 2 things right now:
- start a backup via clicking a button on web ui
- help you check log files

So, there is no screenshot about a search / retrieval function because there is no such function.

**Comment by ThomasWaldmann** [comment]
The UI is intended to help with everyday tasks, it is not intended as a full UI to everything borg can do.

You'll need help of admin to install / configure it, as well as to restore backups.

**Comment by pguth** [comment]
We could add that to the readme.

**Comment by ThomasWaldmann** [comment]
fixed by #128
