### ISSUE TITLE
Status at a glance

### ISSUE THREAD

**Issue by henfri** [borgbackup/borgweb#107]
Hello,

in the past, I used crashplan. Here, I liked that I could see the status of my backup at a glance.
This can be seen here:
http://files.dafacto.com/wp-content/uploads/dafacto/2013/crashplan-report.png
or here:
https://support.code42.com/@api/deki/files/20832/backup-status-report-2016-export.png?revision=1

What I would like to see is:
Overview of hosts that have backed up to this repository. And for each:
-Amount of data that is selected for backup (number of files, amount of data)
-Amount of currently not backed up data  (number of files, amount of data); percentage of backed up data
-Date/Time of Last complete backup

Greetings,
Hendrik

**Comment by ThomasWaldmann** [comment]
just add this to #108.
