### ISSUE TITLE
How to configure Borg for use with borgweb

### ISSUE THREAD

**Issue by henfri** [borgbackup/borgweb#109]
Hello,
I am missing from the documentation, how I need to configure borg so that it writes the appropriate log files.
I.e. what format do the logs from borg need to have, so that they work with borgweb and how do I specify the path to which the logs are saved to by borg?

[I am willing to improve this in the docs myself, if you could provide the information here]

Greetings,
Hendrik

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borgweb/blob/master/borgweb/config.py see there.

the logging.conf is in the toplevel dir.

**Comment by henfri** [comment]
I know the config.py.
the logging.conf is for borgweb.

But I do not know where to point borgweb to for the logs.
Where do I specify the path (and format) *in borg* (not borgweb)

**Comment by ThomasWaldmann** [comment]
no, the logging.conf is for borg, see config.py.

it will all "just work as is" if you are in the toplevel dir of borgweb (like when developping it), have ./repo and ./logs there.

**Comment by henfri** [comment]
I understand that.
But I do not have the logs there. Neither the repo. 
Thus, it does not work.
I know where my repo is, but I do not know where borg stores the logs.
So I do not know what to put into the config.py for the logs

**Comment by ThomasWaldmann** [comment]
the "logs" you see in config.py is a path, you can also point it somewhere else.
as you see in BACKUP_CMD there also, logs are created by redirecting borg's output.

**Comment by henfri** [comment]
Hello,

> logs are created by redirecting borg's output.

That is the information, that I was missing.
Why is that? I mean: why is there no logging (e.g. to /var/log/ by default) in borg?

As we are in borgweb here, I should focus on borgweb issues here. What was a stopper for me is, that the fact that I need to redirect borgs output is not documented in the borgweb documentation.

Greetings,
Hendrik

**Comment by ThomasWaldmann** [comment]
By default it is on your screen, as usual for client programs.
You can then either redirect stderr or configure logging to have it somewhere else.

I/O redirection is standard Linux admin stuff.
And there is also a working example in the config.py provided.

**Comment by henfri** [comment]
Hello,

> By default it is on your screen, as usual for client programs.

Wich is good for programs that usually run in foreground. But for programs that often run in Background, logging to file is useful, I think.

> You can then either redirect stderr
> I/O redirection is standard Linux admin stuff.

Of course. And then I also have to take care of rotating the logs. And I do not know whether I need to redirect stderr only or also stdout. 
Of course, it can all be done. But if there is another program picking up the results, expecting a certain format, then I do not think that stdout/stderr/redirect is good.
But I understand that there is work on this in borg:
https://github.com/borgbackup/borg/pull/422

> or configure logging to have it somewhere else.
Which is not yet implemented, is it?

**Comment by ThomasWaldmann** [comment]
It is implemented.

**Comment by ThomasWaldmann** [comment]
fixed by #110.
