### ISSUE TITLE
Borgweb: installation procedure for explicit python3 path

### ISSUE THREAD

**Issue by dsjstc** [borgbackup/borgweb#111]
Howdy!  I thought I'd give borgweb a try, but the install documentation is not followable for me on Ubuntu 17.10.  There appear to be two competing install procedures.  

The ["stable" install instructions on the main BorgWeb site](http://borgweb.readthedocs.io/en/stable/installation.html#) have only one instruction: `pip install -e .`  This seems predicated on the idea that your path python interpreter is >= python3.4.  My distro doesn't permit this.

The ["latest" install instructions linked to from github](http://borgweb.readthedocs.io/en/latest/installation.html#) also have a 20-line script to set up a "complete dev environment" for "the same virtualenv as you use for BorgBackup".  I don't guess this is targeted at me, as my borg was installed from a distro package.

Any user-targeted documentation would be appreciated, even if it's just "This software is not yet ready to be installed by non-developers".

**Comment by ThomasWaldmann** [comment]
It's all a bit rough still.

I'ld recommend using a virtualenv for borgweb, even if borg is not in there, but installed as a system package.

**Comment by dsjstc** [comment]
Thanks Thomas, I appreciate it. Time for me to go learn a little about virtualenv.
