### ISSUE TITLE
Ability to restore data while backups proceed

### ISSUE THREAD

**Issue by marcpope** [borgbackup/borgweb#112]
When attempting to recover data while a backup is taking place, e.g. borg list reponname, the repo is locked and can't be accomplished. (Tested with 1.1.1)

Consider a scenario of automated backup script every hour, taking 10+ minutes and having to time a restore in between the backups. In this case, you'd have to either cancel the backup script, or turn it off manually.

If possible, please investigate the possibility of mount, list, restore options when a backup is taking place. (does not need to look at the current, on-going backup).

**Comment by ThomasWaldmann** [comment]
This is the borgweb issue tracker, so only borgweb issues should be filed here.
