### ISSUE TITLE
I've made a container for this app

### ISSUE THREAD

**Issue by ppadial** [borgbackup/borgweb#113]
Ey! just to let you know, i have made a docker container for your app.

* Dockerhub url: https://hub.docker.com/r/ppadial/borgweb/
* Github Url: https://github.com/ppadial/docker-borgweb

You can easy use it using:
`docker pull ppadial/borgweb:latest`

If you want to include in your project, so we can use dockerhub to auto-create a docker image on each new version, let me know.

Cheers!

**Comment by ThomasWaldmann** [comment]
Suggestion: add a link via a PR against the community repo?

**Comment by ppadial** [comment]
As you prefer, i have it under my repo, but i can Fork and PR it with no problems. I'll try to do it today.

**Comment by ThomasWaldmann** [comment]
I just meant adding a LINK to your repo there:

https://github.com/borgbackup/community/
