### ISSUE TITLE
js: github complains about vulnerable jquery, upgrade to > 3.0

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borgweb#114]
jQuery 2.x is not maintained any more, update the package.json, test, ...

**Comment by Saman-jafari** [comment]
is someone working on this? if yes I will update the dependencies

**Comment by ThomasWaldmann** [comment]
@Saman-jafari don't think so. feel free to work on it.

In general, if it doesn't look like somebody is working on something, maybe just assume the ticket is free to take and announce in a comment that you are working on it, so other people can see and duplicate work is avoided.

thanks for helping!

**Comment by Saman-jafari** [comment]
Ok I worked on it I update some more dependencies also and checked if everything works fine
