### ISSUE TITLE
Fresh Install error

### ISSUE THREAD

**Issue by Djam94800** [borgbackup/borgweb#117]
Hello everyone,

I installed the git version of borgweb with flask 1.0.2-1. Borg is from also git.
But at launch, borgweb says : 

> Traceback (most recent call last):
>   File "./borgweb", line 11, in <module>
>     sys.exit(main())
>   File "/home/----/.local/lib/python3.6/site-packages/borgweb/app.py", line 29, in main
>     application = create_app()
>   File "/home/----.local/lib/python3.6/site-packages/borgweb/app.py", line 23, in create_app
>     app.error_handler_spec[None][404] = err404
> KeyError: None

Somebody help me please ?
thank you in advance

Djam94200

**Comment by ThomasWaldmann** [comment]
see #116
