### ISSUE TITLE
extract differences/matches between two archives

### ISSUE THREAD

**Issue by leadenhead** [borgbackup/borgweb#132]
Got a question. How can I extract differences or matches between two archives? As far as I understand, there is an opportunity only to display these changes. But I would like to get this behavior:

_Example_:
We have two archives "**first**" and "**second**".
"**first**" contains files "**A**" and "**B**" _(added files "A" and "B")_
"**second**" contains files "**B**" and "**C**" _(file "A" is deleted and file "C" is added)_

Comparing the differences of the archive "**first**" to the archive "**second**", we get the file "**C**".
Comparing the differences of the archive “**second**” to the archive “**first**”, we get the file “**A**”.
Comparing the coincidences between the two archives, we get the file "**B**".

Thanks for your reply!

**Comment by ThomasWaldmann** [comment]
Are you talking about borgweb or borgbackup?

**Comment by leadenhead** [comment]
About borgbackup.
Sorry, I mixed up the topics.
What should I do? Create a question in a suitable place or leave it as is?

**Comment by leadenhead** [comment]
I’d better create a question in the right topic. Thanks!

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/issues/4939
