### ISSUE TITLE
Doesn't work with encrypted backups?

### ISSUE THREAD

**Issue by d2718nis** [borgbackup/borgweb#136]
Hey, just to make sure, it doesn't work with password-protected repositories, right? After clicking on "Start Backup" button I get these logs:

```
127.0.0.1 - - [26/Oct/2020 04:01:47] "GET /backup/status HTTP/1.1" 200 -
127.0.0.1 - - [26/Oct/2020 04:01:47] "GET /backup/status HTTP/1.1" 200 -
127.0.0.1 - - [26/Oct/2020 04:01:47] "GET /backup/status HTTP/1.1" 200 -
Enter passphrase for key /path/to/repo: 127.0.0.1 - - [26/Oct/2020 04:01:47] "GET /backup/status HTTP/1.1" 200 -
127.0.0.1 - - [26/Oct/2020 04:01:48] "GET /backup/status HTTP/1.1" 200 -
127.0.0.1 - - [26/Oct/2020 04:01:48] "GET /backup/status HTTP/1.1" 200 -
127.0.0.1 - - [26/Oct/2020 04:01:48] "GET /backup/status HTTP/1.1" 200 -
127.0.0.1 - - [26/Oct/2020 04:01:48] "GET /backup/status HTTP/1.1" 200 -
...
```

And it will continue requesting /backup/status indefinitely once in a second or so. The only difference on the frontend is that button now states "Stop Backup", but nothing happens under the hood if I get it right.

Thanks.

**Comment by ThomasWaldmann** [comment]
If you automate your backups, you can't have it interactively ask for a passphrase (neither for the borg key, nor for ssh key in case you use a remote repo).

There's `BORG_PASSPHRASE` (see borg docs) and some others to automate answering that question.

**Comment by d2718nis** [comment]
So, theoretically the best way is to add `BORG_PASSPHRASE` or even `BORG_PASSCOMMAND` at the beginning of the `BACKUP_CMD` config value, right?

https://github.com/borgbackup/borgweb/blob/master/borgweb/config.py#L24

**Comment by ThomasWaldmann** [comment]
For example, yes.
