### ISSUE TITLE
Screenshot broken - status of the project?

### ISSUE THREAD

**Issue by tholu** [borgbackup/borgweb#137]
![CleanShot 2021-04-20 at 13 38 23](https://user-images.githubusercontent.com/316763/115389709-b4e9d600-a1dd-11eb-9027-47f8312d8f3e.png)

The BorgWeb screenshot is broken (see screenshot above). Is the project still active?

**Comment by mmagnus** [comment]
I guess the project is active, the screenshots goes to https://cdn.pbrd.co/images/vYSNCBV.png and https://cdn.pbrd.co is down.

**Comment by DanielRamp** [comment]
Just if someone is also interested, I could find a old version in the Internet Archive Wayback Machine:
https://web.archive.org/web/20181230231308/https://cdn.pbrd.co/images/vYSNCBV.png
direkt to the image:
https://web.archive.org/web/20181230231308if_/https://cdn.pbrd.co/images/vYSNCBV.png
![alt](https://web.archive.org/web/20181230231308if_/https://cdn.pbrd.co/images/vYSNCBV.png)

I think if that was actually the image (its from 2018 so probably not), there is a nicer design work in progress #131.

**Comment by duven87** [comment]
Hello! and despite not being updated for 3 years, is borgweb still compatible with the new versions of borg backup?

**Comment by williamdes** [comment]
I had posted in #142
https://github.com/borgbackup/borgweb/blob/e609ec48257faa45ae3a7b9daaab0590fa897304/README.rst?plain=1#L1

it's been a while since it's broken, here is the image: https://web.archive.org/web/20180725064925/https://cdn.pbrd.co/images/vYSNCBV.png
