### ISSUE TITLE
borgweb doesn't tell users that they must use -e repokey during borg init

### ISSUE THREAD

**Issue by dykstranet** [borgbackup/borgweb#140]
I initialized my borg repo with keyfile, and found the borgweb backup to be not functioning. When I tested on a throwaway repo with repokey mode, it worked. `borgweb` should have told user of this limitation.

**Comment by ThomasWaldmann** [comment]
Hmm, borgweb just invokes `borg create` via the commandline.

So I guess if the key is available on the machine and for the user doing that, all modes (repokey, keyfile and no encryption / no authentication / no key) should work?

**Comment by dykstranet** [comment]
Thanks for your reply. I think the CLI will work for my purposes for now.
