### ISSUE TITLE
/borg-env/bin/borgweb: No such file or directory

### ISSUE THREAD

**Issue by Khazhi** [borgbackup/borgweb#141]
Hi all!
Maybe a stupid question but I don't know what to do anymore.

> I follow the instructions
> Install Python code and dependencies:
> virtualenv --python=python3 borg-env
> source borg-env/bin/activate
> pip install tox pytest
> git clone https://github.com/borgbackup/borgweb.git
> cd borg web
> pip install -e .
> 
> Install JS code and dependencies:
> cd js
> npm install
> 
> Start the local Flask webserver:
> cd ../../
> mkdir logs
> ./borg-env/bin/borgweb
> 
>  Start the watch process and Browsersync
>  In another shell navigate to `borgweb/js` and enter:
> gulp watch

Everything is downloading.
Catalog are created
But when it comes to ./borg-env/bin/borgweb it swears that there is no such file or directory
debian system 10.0.0
Tell me, what is this file? or is it a directory?
I just want to understand what is missing.
I'm sorry, I'm currently learning

**Comment by ThomasWaldmann** [comment]
As long as you have the virtual env active, you could just invoke `borgweb` because it is in the PATH then.
