### ISSUE TITLE
Display in log list if the respective log failed

### ISSUE THREAD

**Issue by pguth** [borgbackup/borgweb#34]

**Comment by ThomasWaldmann** [comment]
note: if the list of logs is long, this would need to open many logs and at least read and classify their last line(s). not sure if we want to slow down by doing that.

**Comment by pguth** [comment]
@ThomasWaldmann I guess we could do this for the maybe 8 most recent logs or so.

**Comment by ThomasWaldmann** [comment]
@pguth yes, latest few is ok.

**Comment by pguth** [comment]
509f0becdae293d2d325fec13f7cb05c91a05bf8
