### ISSUE TITLE
Better log files

### ISSUE THREAD

**Issue by pguth** [borgbackup/borgweb#65]
Just to link this up properly: borgbackup/borg/issues/58

> Determine success state and have it in the log file for easy readout (see borgbackup/borgweb#35).

**Comment by pguth** [comment]
For ref.: borgbackup/borgweb/issues/49

**Comment by pguth** [comment]
New: `/logs/x/` will also print out the maximum file offset.

**Comment by pguth** [comment]
```
N=0 -> "successfully"
N=1 -> "normally, but with warnings"
N=2 -> "due to an error"
```

We covered 0 and 2 in the current UI. Let's add 1 too.

**Comment by ThomasWaldmann** [comment]
Note that in the past 1 meant error, now it is warning. 2 means error now.

there is also a new very last log entry that ends with "rc X".

**Comment by ThomasWaldmann** [comment]
rc 1 works already, also the borg issues are closed.

so what's left is getting logs with INFO, ERROR, WARNING state on each line.

**Comment by ThomasWaldmann** [comment]
Fixed by:
https://github.com/borgbackup/borgweb/commit/066e1fc00b3bb32dba5a3dd5807cae81d68496fb
