### ISSUE TITLE
Output information on the error

### ISSUE THREAD

**Issue by pguth** [borgbackup/borgweb#78]
The web frontend could display tracebacks etc.

**Comment by ThomasWaldmann** [comment]
rather give an error msg than a traceback.

**Comment by ThomasWaldmann** [comment]
hmm, issue description needs to be more precise. @pguth do you still remember about what tracebacks / errors this was about? Where did the tracebacks happen?

**Comment by ThomasWaldmann** [comment]
closing this, see previous comment.
