### ISSUE TITLE
template structure needs improvement

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borgweb#79]
tried to make a nice 404 page, rendering it somehow inside the "theme" using this templates/404.html:

```
{% extends "_layout.html" %}

{% block content %}
<p>404 Not found.</p>
{% endblock %}
```

But that somehow looks unexpectedly crappy...

**Comment by pguth** [comment]
Not reproducible. Error page template improved via 97b064e2c241ad2160ccdbd359fd8df99cd45c79
