### ISSUE TITLE
feature request: take a look at duplicati 2.0 web interface for inspiration

### ISSUE THREAD

**Issue by bedros** [borgbackup/borgweb#91]
Hi all,

I'm using borgbackup from command line and after looking for some alternative open source backup for windows, I came across duplicati 2.0 which is not released yet, but it had some amazing easy to use web interface for backup; worth checking out.

specifically, 

how the UI guides you to setup the backup configs with ? to show you options
how it lists backup jobs and when clicked you can run the job, modify, restore etc.

http://www.duplicati.com/howtos/how-to-install-and-run-duplicati-2-0-preview

Thanks,

Bedros

**Comment by ThomasWaldmann** [comment]
There's a lot else to do first, even if we considered extending the scope to more than "view the logs, start a backup".

So, that needs to be done first (see milestones) and then there would be a need for many more developers - doing a more extensive UI is also a lot of work.

**Comment by milkey-mouse** [comment]
Looks like that link is broken, here's the [archive.org copy](https://web.archive.org/web/20160918172048/https://www.duplicati.com/howtos/how-to-install-and-run-duplicati-2-0-preview).
