### ISSUE TITLE
update screenshot in docs

### ISSUE THREAD

**Issue by ThomasWaldmann** [borgbackup/borgweb#92]
the log format shown there is not up-to-date any more.

**Comment by ThomasWaldmann** [comment]
this should be done as one of the last steps before release (after all frontend changes are done).

**Comment by rugk** [comment]
Still broken 4 years later… :pleading_face:

**Comment by zhiga-rsp** [comment]
![image](https://github.com/borgbackup/borgweb/assets/17156118/a97eea08-5ae6-4ba4-8972-a2cc8438cd95)
There is no image. Would it be fixed?

**Comment by ThomasWaldmann** [comment]
@zhiga-rsp I removed the broken link. The textual description below says it all.
