### ISSUE TITLE
Info for initial setup is missing in the docs

### ISSUE THREAD

**Issue by devnope** [borgbackup/borgweb#97]
I'd like to give borgweb a try, because I'm happy with borgbackup itself.
Yet I haven't found an description, how to tell borgweb to give me a fancypantsy webview of my backups.
I'd expect a borgbackup.conf, where I simply specify params like naming, source and destinations, possibly ssh keys for the transfer, etc. and a document, which tells me: "hey smartass, create a config file and fill it with somethink like $foo" 
I don't know where your journey goes, so, if you like support, what can I do to make borgweb more usable?

**Comment by ThomasWaldmann** [comment]
Try the "latest" doc, it is more complete and better readable than "stable" docs:

http://borgweb.readthedocs.io/en/latest/

**Comment by dlmetcalf** [comment]
You *really* need to put at least a link to that on the website and in the README on GitHub. No one's going to know about it here. 99% of people who try to use your app are going to fall over otherwise and most probably won't search for an issue.

**Comment by ThomasWaldmann** [comment]
ok, github headline and readme now links to latest docs.
