### ISSUE TITLE
Configure a different hostname than "localhost"

### ISSUE THREAD

**Issue by SR-G** [borgbackup/borgweb#98]
Hey.
I know anything about python and can't find the information by myself, so sorry if this is already covered.
I'm trying to run borgweb in a docker container, and i can't have the web port routed outside the container.
It's probably because the web server is running against "localhost" and not "0.0.0.0".

How can i change the hostname used by the webserver ?!
I've found nothing about that.
Changing borgweb/config.py ("NAME" property) doesn't help.

Any idea ?

**Comment by ThomasWaldmann** [comment]
Yes, the default is localhost:5000 - and it was not configurable with the code you used.

I added configurability now, see there:

https://github.com/borgbackup/borgweb/commit/a9e694d4b3da971302f9ea40b354966233509e76

So, just try latest master and have a look into config.py again.
